<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LurkBait.NegativeCatches</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GameManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(GameManagedDir)\UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ParticleImage">
      <HintPath>$(GameManagedDir)\ParticleImage.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
